import base64
import io
from datetime import datetime, timezone

import numpy as np
import qrcode
from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

BRAND_DARK = colors.HexColor("#22301f")
BRAND_ACCENT = colors.HexColor("#3e8a6c")
WARN_AMBER = colors.HexColor("#8f6a24")
MUTED = colors.HexColor("#6b6b60")
LINE = colors.HexColor("#d8d5c9")

DISCLAIMER = (
    "This report was generated by an automated AI screening system and is "
    "decision support only — it is not a substitute for clinical diagnosis. "
    "All findings must be confirmed by a qualified ophthalmologist."
)


def _iso_now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _qr_png_bytes(data):
    img = qrcode.make(data, box_size=6, border=2)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def _rl_image_from_b64(b64, width):
    """Decode base64 PNG into a flowable Image, preserving aspect ratio."""
    try:
        raw = base64.b64decode(b64)
        with PILImage.open(io.BytesIO(raw)) as im:
            w, h = im.size
        buf = io.BytesIO(raw)
        return Image(buf, width=width, height=width * h / max(w, 1))
    except Exception:
        return None


def findings_text(lesions):
    if not lesions:
        return "No lesion-level segmentation results available for this examination."
    detected, absent = [], []
    for info in lesions.values():
        if info.get("detected"):
            detected.append(info["name"])
        else:
            absent.append(info["name"])
    if not detected:
        return (
            "No diabetic retinopathy lesions were detected above the reporting "
            "threshold in the segmented fundus image."
        )
    sentences = []
    for name in sorted(detected):
        if name == "Hard Exudates":
            sentences.append("Scattered hard exudates detected")
        elif name == "Microaneurysms":
            sentences.append("Microaneurysms present")
        elif name == "Hemorrhages":
            sentences.append("Retinal hemorrhages present")
        elif name == "Cotton Wool Spots":
            sentences.append("Cotton wool spots identified")
    return ". ".join(sentences) + f". Not detected: {', '.join(sorted(absent))}." if absent else ". ".join(sentences) + "."


def generate_pdf_report(payload) -> bytes:
    """Build the clinical PDF from a cached /api/predict result payload."""
    patient_id = payload.get("patient_id", "unknown")
    classification = payload.get("classification") or {}
    quality = payload.get("quality") or {}
    referral = payload.get("referral") or {}
    seg = payload.get("segmentation") or {}
    needs_review = bool(payload.get("needs_human_review"))
    generated_at = _iso_now()

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("brand", parent=styles["Title"], fontSize=20, textColor=BRAND_DARK, alignment=TA_CENTER, spaceAfter=2)
    subtitle = ParagraphStyle("sub", parent=styles["Normal"], fontSize=9.5, textColor=MUTED, alignment=TA_CENTER)
    section = ParagraphStyle(
        "section", parent=styles["Heading2"], fontSize=11.5, textColor=BRAND_ACCENT,
        spaceBefore=10, spaceAfter=4,
    )
    body = ParagraphStyle("body", parent=styles["Normal"], fontSize=9.5, leading=13.5, textColor=colors.HexColor("#333330"))
    warn = ParagraphStyle("warn", parent=body, textColor=WARN_AMBER)

    story = [
        Paragraph("RetinaScan AI", h1),
        Paragraph("Diabetic Retinopathy Screening · Clinical Summary Report", subtitle),
        Spacer(1, 4 * mm),
    ]

    meta_rows = [
        ["Patient ID", str(patient_id), "Generated (UTC)", generated_at],
        ["Fundus score", str(quality.get("fundus_score", "—")), "Blur score", str(quality.get("blur_score", "—"))],
    ]
    meta_tbl = Table(meta_rows, colWidths=[28 * mm, 55 * mm, 32 * mm, 55 * mm])
    meta_tbl.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
        ("TEXTCOLOR", (2, 0), (2, -1), MUTED),
        ("GRID", (0, 0), (-1, -1), 0.4, LINE),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story += [meta_tbl]

    stage_label = classification.get("label", "Unknown")
    conf = classification.get("confidence")
    story += [
        Paragraph("ICDR Classification", section),
        Paragraph(
            f"Predicted severity: <b>Stage {classification.get('stage', '?')} — {stage_label}</b>"
            + (f" &nbsp;(model confidence {conf * 100:.1f}%)" if isinstance(conf, (int, float)) else ""),
            body,
        ),
    ]
    if needs_review:
        reasons = ", ".join(payload.get("review_reasons") or [])
        story.append(
            Paragraph(
                "<b>Flagged for human review:</b> model confidence/quality below the abstention threshold"
                + (f" ({reasons})" if reasons else "")
                + ". The stage above is a suggestion only and must be confirmed by a clinician.",
                warn,
            )
        )

    story += [Paragraph("Findings", section), Paragraph(findings_text(seg.get("lesions")), body)]

    images = [("Preprocessed fundus", seg.get("original")), ("Lesion overlay", seg.get("overlay"))]
    if payload.get("attention"):
        images.append(("AI attention (Grad-CAM)", payload["attention"]))
    img_cells, widths = [], []
    slot = 52 * mm if len(images) == 3 else (78 * mm if len(images) == 2 else 160 * mm)
    for caption, b64 in images:
        flow = _rl_image_from_b64(b64, slot)
        cell = [flow, Paragraph(caption, ParagraphStyle("cap", parent=subtitle, spaceBefore=2))] if flow else [Paragraph("(image unavailable)", subtitle)]
        img_cells.append(cell)
        widths.append(slot + 4 * mm)
    if img_cells:
        img_tbl = Table([img_cells], colWidths=widths, hAlign="CENTER")
        img_tbl.setStyle(TableStyle([("ALIGN", (0, 0), (-1, -1), "CENTER"), ("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
        story += [Paragraph("Images", section), img_tbl]

    ref_txt = (
        f"Referral recommended: <b>{referral.get('urgency', 'clinical review')}</b>."
        if referral.get("recommended")
        else f"No urgent referral indicated. Follow-up: {referral.get('urgency', 'routine annual screening')}."
    )
    story += [Paragraph("Referral Guidance", section), Paragraph(ref_txt, body)]

    qr_cell = Image(io.BytesIO(_qr_png_bytes(f"retinascan://report/{patient_id}?ts={generated_at}")), width=24 * mm, height=24 * mm)
    footer_tbl = Table([[qr_cell, Paragraph(DISCLAIMER, ParagraphStyle("disc", parent=body, fontSize=8, leading=11, textColor=MUTED))]],
                       colWidths=[30 * mm, 140 * mm])
    footer_tbl.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("ALIGN", (0, 0), (0, 0), "CENTER"),
                                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                                    ("LINEABOVE", (0, 0), (-1, 0), 0.6, LINE)]))
    story += [Spacer(1, 8 * mm), footer_tbl]

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=14 * mm, bottomMargin=12 * mm,
                            leftMargin=18 * mm, rightMargin=18 * mm, title=f"RetinaScan AI Report {patient_id}")
    doc.build(story)
    return buf.getvalue()
